// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL6NMlBD81O8iYt5uQRSqZCwAiOOP9niI',
    appId: '1:1088655836231:web:9c40b2e0aff918b1315d62',
    messagingSenderId: '1088655836231',
    projectId: 'cuinacompartida-b4186',
    authDomain: 'cuinacompartida-b4186.firebaseapp.com',
    storageBucket: 'cuinacompartida-b4186.appspot.com',
    measurementId: 'G-SG54MQF5W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7GBJ_lK49-ftUPjVsBYYh0k-ZQPDVW1c',
    appId: '1:1088655836231:android:dfca92eb290a8d47315d62',
    messagingSenderId: '1088655836231',
    projectId: 'cuinacompartida-b4186',
    storageBucket: 'cuinacompartida-b4186.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAlFll1sIV2wRhDYZg4gP6hOEWeYa2DyE',
    appId: '1:1088655836231:ios:9b596009d4f3c9f1315d62',
    messagingSenderId: '1088655836231',
    projectId: 'cuinacompartida-b4186',
    storageBucket: 'cuinacompartida-b4186.appspot.com',
    iosBundleId: 'com.example.loginProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAlFll1sIV2wRhDYZg4gP6hOEWeYa2DyE',
    appId: '1:1088655836231:ios:19ad8f2bc72b9697315d62',
    messagingSenderId: '1088655836231',
    projectId: 'cuinacompartida-b4186',
    storageBucket: 'cuinacompartida-b4186.appspot.com',
    iosBundleId: 'com.example.loginProject.RunnerTests',
  );
}
